module.exports = {
  en: {
    switchLocale: "En fran\u00e7ais svp",
    whoAmI: "Who I am",
    whatIDo: "What I do",
    cv: "Resume",
    openToWork: "Currently open to new opportunities as a Senior Developer or Tech Lead.",
    skills: "As a list",
    skillsInfra: "Infrastructure",
    skillsTransversal: "Transversal",
    skillsVisuals: "Visuals",
    skillsVisualSoftware: "Sketch, Photoshop, Illustrator & friends",
    commentAlreadySaid: "you said it already",
    commentUsingWebsite: "Because using a website is a skill now ?",
    readMore: "read more",
    back: "back",
    sectionRecent: "Recent work",
    sectionPast: "Earlier work",
    connectTitle: "Connect",
    connectDesc: "As the sole engineer at NEO-OOH (Quebecor Media), I designed and built their entire internal platform from scratch, from stack selection and architecture to database design, UI, and deployment.",
    dvinTitle: "DVin",
    dvinDesc: "A Web3 platform for tokenized wine bottles built on Solana. Users buy, trade, and redeem Digital Corks (NFTs) representing real wine bottles.",
    autotraderTitle: "AutoTrader",
    autotraderDesc: "A personal algorithmic trading platform built on Interactive Brokers. Backtesting, Bayesian optimization, and live execution across 11+ trading algorithms.",
    dealershipTitle: "Dealership Analytics",
    dealershipDesc: "Sales data analysis platform for car dealerships. Work in progress.",
    neoTitle: "Neo-OOH",
    neoDesc: "Before Connect, I built multiple projects for Neo-OOH as a freelance developer: their public website, a content management platform handling 60M+ monthly impressions, and real-time dynamic content systems.",
    prismeTitle: "Prisme",
    prismeDesc: "Interactive and immersive art installations combining technology and ontological questioning, as part of a six-person artist collective.",
    runnerTitle: "Runner",
    runnerDesc: "A fast fuzzy finder for TouchDesigner",
    tdLibraryTitle: "TouchDesigner Library",
    tdLibraryDesc: "A collection of reusable components made to ease the learning curve of TouchDesigner and improve its accessibility.",
    connectPageTitle: "Connect",
    dvinPageTitle: "DVin",
    autotraderPageTitle: "AutoTrader",
    neoTrafficPageTitle: "Neo Traffic",
    prismePageTitle: "Prisme collective",
    tdLibraryPageTitle: "TouchDesigner library",
    runnerPageTitle: "Runner"
  },
  fr: {
    switchLocale: "in english pls",
    whoAmI: "Qui je suis",
    whatIDo: "Ce que je fais",
    cv: "Curriculum Vitae",
    openToWork: "Actuellement ouvert \u00e0 de nouvelles opportunit\u00e9s en tant que D\u00e9veloppeur Senior ou Lead Technique.",
    skills: "En liste",
    skillsInfra: "Infrastructure",
    skillsTransversal: "Transversale",
    skillsVisuals: "Visuel",
    skillsVisualSoftware: "Sketch, Photoshop, Illustrator et leurs copains",
    commentAlreadySaid: "Tu l\u2019as d\u00e9j\u00e0 dit",
    commentUsingWebsite: "Parce qu\u2019utiliser un site web est une comp\u00e9tence maintenant ?",
    readMore: "lire la suite",
    back: "retour",
    sectionRecent: "Travaux r\u00e9cents",
    sectionPast: "Travaux ant\u00e9rieurs",
    connectTitle: "Connect",
    connectDesc: "En tant que seul d\u00e9veloppeur chez NEO-OOH (Qu\u00e9becor Media), j\u2019ai con\u00e7u et construit l\u2019int\u00e9gralit\u00e9 de leur plateforme interne de z\u00e9ro, du choix du stack et de l\u2019architecture \u00e0 la base de donn\u00e9es, l\u2019interface et le d\u00e9ploiement.",
    dvinTitle: "DVin",
    dvinDesc: "Une plateforme Web3 de bouteilles de vin tokenis\u00e9es sur Solana. Les utilisateurs ach\u00e8tent, \u00e9changent et utilisent des Digital Corks (NFTs) repr\u00e9sentant de vraies bouteilles.",
    autotraderTitle: "AutoTrader",
    autotraderDesc: "Une plateforme personnelle de trading algorithmique sur Interactive Brokers. Backtesting, optimisation bay\u00e9sienne, et ex\u00e9cution en direct avec plus de 11 algorithmes.",
    dealershipTitle: "Analytique Concessionnaires",
    dealershipDesc: "Plateforme d\u2019analyse de donn\u00e9es de vente pour concessionnaires automobiles. En cours de d\u00e9veloppement.",
    neoTitle: "Neo-OOH",
    neoDesc: "Avant Connect, j\u2019ai r\u00e9alis\u00e9 plusieurs projets pour Neo-OOH en tant que d\u00e9veloppeur freelance: leur site public, une plateforme de gestion de contenu g\u00e9rant plus de 60M d\u2019impressions par mois, et des syst\u00e8mes de contenu dynamique en temps r\u00e9el.",
    prismeTitle: "Prisme",
    prismeDesc: "Installations artistiques interactives et immersives m\u00ealant technologie et questionnements ontologiques, au sein d\u2019un collectif de six artistes.",
    runnerTitle: "Runner",
    runnerDesc: "Un fuzzy-finder rapide pour TouchDesigner",
    tdLibraryTitle: "Biblioth\u00e8que TouchDesigner",
    tdLibraryDesc: "Une collection d\u2019\u00e9l\u00e9ments r\u00e9utilisables permettant de faciliter l\u2019apprentissage de TouchDesigner et d\u2019en am\u00e9liorer l\u2019affordance.",
    connectPageTitle: "Connect",
    dvinPageTitle: "DVin",
    autotraderPageTitle: "AutoTrader",
    neoTrafficPageTitle: "Neo Traffic",
    prismePageTitle: "Collectif Prisme",
    tdLibraryPageTitle: "Biblioth\u00e8que TouchDesigner",
    runnerPageTitle: "Runner"
  }
};
