module.exports = {
  en: {
    switchLocale: "En fran\u00e7ais svp",
    whoAmI: "About",
    whatIDo: "Work",
    cv: "Resume",
    openToWork: "Currently open to new opportunities as a Senior Developer or Tech Lead.",
    skills: "As a list",
    skillsInfra: "Infrastructure",
    skillsTransversal: "Transversal",
    skillsVisuals: "Visuals",
    skillsVisualSoftware: "Sketch, Photoshop, Illustrator & friends",
    commentAlreadySaid: "you said it already",
    commentUsingWebsite: "Because using a website is a skill now ?",
    readMore: "read more",
    back: "back",
    sectionRecent: "Recent work",
    sectionPast: "Earlier work",
    connectTitle: "Connect",
    connectDesc: "As the sole engineer at NEO-OOH (Quebecor Media), I designed and built their entire internal platform from scratch, from stack selection and architecture to database design, UI, and deployment.",
    dvinTitle: "DVin",
    dvinDesc: "I designed and built DVin end-to-end — a Web3 platform on Solana where users buy, trade, and redeem tokenized wine bottles as NFTs. Django backend, React frontend, on-chain minting/transfer/burn logic, and an AI-powered wine recommendation chatbot.",
    autotraderTitle: "AutoTrader",
    autotraderDesc: "A production algorithmic trading platform I built on Interactive Brokers. 13-service microservices architecture with Laravel, FastAPI, React, and Bayesian optimization via Optuna. 11+ live algorithms ranging from FFT cycle analysis to LSTM signal trading.",
    neoTitle: "Neo-OOH",
    neoDesc: "Before Connect, I built multiple projects for Neo-OOH as a freelance developer: their public website, a content management platform handling 60M+ monthly impressions, and real-time dynamic content systems.",
    prismeTitle: "Prisme",
    prismeDesc: "Interactive art installations built with a six-person collective — multi-sensor tracking, real-time speech analysis, and conversational AI driving immersive physical experiences.",
    runnerTitle: "Runner",
    runnerDesc: "A fast fuzzy finder for TouchDesigner",
    tdLibraryTitle: "TouchDesigner Library",
    tdLibraryDesc: "A collection of reusable components made to ease the learning curve of TouchDesigner and improve its accessibility.",
    connectPageTitle: "Connect",
    dvinPageTitle: "DVin",
    autotraderPageTitle: "AutoTrader",
    neoTrafficPageTitle: "Neo Traffic",
    prismePageTitle: "Prisme collective",
    tdLibraryPageTitle: "TouchDesigner library",
    runnerPageTitle: "Runner"
  },
  fr: {
    switchLocale: "in english pls",
    whoAmI: "À propos",
    whatIDo: "Travaux",
    cv: "Curriculum Vitae",
    openToWork: "Actuellement ouvert \u00e0 de nouvelles opportunit\u00e9s en tant que D\u00e9veloppeur Senior ou Lead Technique.",
    skills: "En liste",
    skillsInfra: "Infrastructure",
    skillsTransversal: "Transversale",
    skillsVisuals: "Visuel",
    skillsVisualSoftware: "Sketch, Photoshop, Illustrator et leurs copains",
    commentAlreadySaid: "Tu l\u2019as d\u00e9j\u00e0 dit",
    commentUsingWebsite: "Parce qu\u2019utiliser un site web est une comp\u00e9tence maintenant ?",
    readMore: "lire la suite",
    back: "retour",
    sectionRecent: "Travaux r\u00e9cents",
    sectionPast: "Travaux ant\u00e9rieurs",
    connectTitle: "Connect",
    connectDesc: "En tant que seul d\u00e9veloppeur chez NEO-OOH (Qu\u00e9becor Media), j\u2019ai con\u00e7u et construit l\u2019int\u00e9gralit\u00e9 de leur plateforme interne de z\u00e9ro, du choix du stack et de l\u2019architecture \u00e0 la base de donn\u00e9es, l\u2019interface et le d\u00e9ploiement.",
    dvinTitle: "DVin",
    dvinDesc: "J\u2019ai con\u00e7u et construit DVin de bout en bout \u2014 une plateforme Web3 sur Solana o\u00f9 les utilisateurs ach\u00e8tent, \u00e9changent et utilisent des bouteilles de vin tokenis\u00e9es en NFTs. Backend Django, frontend React, logique on-chain de minting/transfert/burn, et un chatbot IA de recommandation de vins.",
    autotraderTitle: "AutoTrader",
    autotraderDesc: "Une plateforme de trading algorithmique en production sur Interactive Brokers. Architecture microservices de 13 services avec Laravel, FastAPI, React, et optimisation bay\u00e9sienne via Optuna. Plus de 11 algorithmes actifs, de l\u2019analyse de cycles FFT au trading par signaux LSTM.",
    neoTitle: "Neo-OOH",
    neoDesc: "Avant Connect, j\u2019ai r\u00e9alis\u00e9 plusieurs projets pour Neo-OOH en tant que d\u00e9veloppeur freelance: leur site public, une plateforme de gestion de contenu g\u00e9rant plus de 60M d\u2019impressions par mois, et des syst\u00e8mes de contenu dynamique en temps r\u00e9el.",
    prismeTitle: "Prisme",
    prismeDesc: "Installations artistiques interactives cr\u00e9\u00e9es au sein d\u2019un collectif de six artistes \u2014 tracking multi-capteurs, analyse vocale en temps r\u00e9el, et IA conversationnelle au service d\u2019exp\u00e9riences physiques immersives.",
    runnerTitle: "Runner",
    runnerDesc: "Un fuzzy-finder rapide pour TouchDesigner",
    tdLibraryTitle: "Biblioth\u00e8que TouchDesigner",
    tdLibraryDesc: "Une collection d\u2019\u00e9l\u00e9ments r\u00e9utilisables permettant de faciliter l\u2019apprentissage de TouchDesigner et d\u2019en am\u00e9liorer l\u2019affordance.",
    connectPageTitle: "Connect",
    dvinPageTitle: "DVin",
    autotraderPageTitle: "AutoTrader",
    neoTrafficPageTitle: "Neo Traffic",
    prismePageTitle: "Collectif Prisme",
    tdLibraryPageTitle: "Biblioth\u00e8que TouchDesigner",
    runnerPageTitle: "Runner"
  }
};
